#include "elastos/chubbamorris/CRegulator.h"
#include <stdio.h>

using Elastos::Core::EIID_IComparable;

namespace Elastos {
namespace ChubbaMorris {

// The class which implements a CAR interface requires macros CAR_INTERFACE_IMPL/CAR_INTERFACE_IMPL
CAR_INTERFACE_IMPL(CRegulator, Object, ICH, IComparable)

// Initialize member variables using member initialization lists.
CRegulator::CRegulator()
    : mSetAuditorFinancial_AuditorFinancialId("String")
    , mGetAuditorFinancial_AuditorFinancialId("String")
    , mSetAuditorFinancial_Name("String")
    , mGetAuditorFinancial_AuditorFinancialId("String")
    , mSetAuditorFinancial_ContactFirstNameList(["String"])
    , mGetAuditorFinancial_ContactFirstNameList(["String"])
    , mSetAuditorFinancial_ContactLastNameList(["String"])
    , mGetAuditorFinancial_ContactLastNameList(["String"])
    , mSetAuditorFinancial_StreetAddress("String")
    , mGetAuditorFinancial_StreetAddress("String")
    , mSetAuditorFinancial_PostalAddress("String")
    , mGetAuditorFinancial_PostalAddress("String")
    , mSetAuditorFinancial_EmailAddresses(["String"])
    , mGetAuditorFinancial_EmailAddresses(["String"])
    , mSetAuditorFinancial_MobilePhone(["String"])
    , mGetAuditorFinancial_MobilePhone(["String"])
    , mSetAuditorFinancial_WorkPhone(["String"])
    , mGetAuditorFinancial_WorkPhone(["String"])
    , mSetAuditorFinancial_ContactedWithDetails(["String"])
    , mGetAuditorFinancial_ContactedWithDetails(["String"])
    , mSetAuditorFinancial_DocRefIds(["String"])
    , mGetAuditorFinancial_DocRefIds(["String"])
    , mSetAuditorFinancial_BusinessChannelOwnerId("String")
    , mGetAuditorFinancial_BusinessChannelOwnerId("String")
    , mSetSecurityAuditor_SecurityAuditorId("String")
    , mGetSecurityAuditor_SecurityAuditorId("String")
    , mSetSecurityAuditor_Name("String")
    , mSetSecurityAuditor_ContactFirstNameList(["String"])
    , mGetSecurityAuditor_ContactFirstNameList(["String"])
    , mSetSecurityAuditor_ContactLastNameList(["String"])
    , mGetSecurityAuditor_ContactLastNameList(["String"])
    , mSetSecurityAuditor_StreetAddress("String")
    , mGetSecurityAuditor_StreetAddress("String")
    , mSetSecurityAuditor_PostalAddress("String")
    , mGetSecurityAuditor_PostalAddress("String")
    , mSetSecurityAuditor_EmailAddresses(["String"])
    , mGetSecurityAuditor_EmailAddresses(["String"])
    , mSetSecurityAuditor_MobilePhone(["String"])
    , mGetSecurityAuditor_MobilePhone(["String"])
    , mSetSecurityAuditor_WorkPhone(["String"])
    , mGetSecurityAuditor_WorkPhone(["String"])
    , mSetSecurityAuditor_ContactedWithDetails(["String"])
    , mGetSecurityAuditor_ContactedWithDetails(["String"])
    , mSetSecurityAuditor_DocRefIds(["String"])
    , mGetSecurityAuditor_DocRefIds(["String"])
    , mSetSecurityAuditor_BusinessChannelOwnerId("String")
    , mGetSecurityAuditor_BusinessChannelOwnerId("String")
    , mSetCommunityHousingRegulator_CommunityHousingRegulatorId("String")
    , mGetCommunityHousingRegulator_CommunityHousingRegulatorId("String")
    , mSetCommunityHousingRegulator_AuthorityName("String")
    , mGetCommunityHousingRegulator_AuthorityName("String")
    , mSetCommunityHousingRegulator_ContactFirstNameList(["String"])
    , mGetCommunityHousingRegulator_ContactFirstNameList(["String"])
    , mSetCommunityHousingRegulator_ContactLastNameList(["String"])
    , mGetCommunityHousingRegulator_ContactLastNameList(["String"])
    , mSetCommunityHousingRegulator_StreetAddress("String")
    , mGetCommunityHousingRegulator_StreetAddress("String")
    , mSetCommunityHousingRegulator_PostalAddress("String")
    , mGetCommunityHousingRegulator_PostalAddress("String")
    , mSetCommunityHousingRegulator_EmailAddresses(["String"])
    , mGetCommunityHousingRegulator_EmailAddresses(["String"])
    , mSetCommunityHousingRegulator_MobilePhone(["String"])
    , mGetCommunityHousingRegulator_MobilePhone(["String"])
    , mSetCommunityHousingRegulator_WorkPhone(["String"])
    , mGetCommunityHousingRegulator_WorkPhone(["String"])
    , mSetCommunityHousingRegulator_ContactedWithDetails(["String"])
    , mGetCommunityHousingRegulator_ContactedWithDetails(["String"])
    , mSetCommunityHousingRegulator_AusStates(["String"])
    , mGetCommunityHousingRegulator_AusStates(["String"])
    , mSetCommunityHousingRegulator_DocRefIds(["String"])
    , mGetCommunityHousingRegulator_DocRefIds(["String"])
    , mSetCommunityHousingRegulator_ImageRefIds(["String"])
    , mGetCommunityHousingRegulator_ImageRefIds(["String"])
    , mSetCommunityHousingRegulator_BusinessChannelOwnerId("String")
    , mGetCommunityHousingRegulator_BusinessChannelOwnerId("String")
    , mSetRentalBondAuthority_RentalBondAuthorityId("String")
    , mGetRentalBondAuthority_RentalBondAuthorityId("String")
    , mSetRentalBondAuthority_AuthorityName("String")
    , mGetRentalBondAuthority_AuthorityName("String")
    , mSetRentalBondAuthority_AusState("String")
    , mGetRentalBondAuthority_AusState("String")
    , mSetRentalBondAuthority_ContactFirstNameList(["String"])
    , mGetRentalBondAuthority_ContactFirstNameList(["String"])
    , mSetRentalBondAuthority_ContactLastNameList(["String"])
    , mGetRentalBondAuthority_ContactLastNameList(["String"])
    , mSetRentalBondAuthority_StreetAddress("String")
    , mGetRentalBondAuthority_StreetAddress("String")
    , mSetRentalBondAuthority_PostalAddress("String")
    , mGetRentalBondAuthority_PostalAddress("String")
    , mSetRentalBondAuthority_EmailAddresses(["String"])
    , mGetRentalBondAuthority_EmailAddresses(["String"])
    , mSetRentalBondAuthority_MobilePhone(["String"])
    , mGetRentalBondAuthority_MobilePhone(["String"])
    , mSetRentalBondAuthority_WorkPhone(["String"])
    , mGetRentalBondAuthority_WorkPhone(["String"])
    , mSetRentalBondAuthority_ContactedWithDetails(["String"])
    , mGetRentalBondAuthority_ContactedWithDetails(["String"])
    , mSetRentalBondAuthority_BusinessChannelOwnerId("String")
    , mGetRentalBondAuthority_BusinessChannelOwnerId("String")
    , mSetRentalBondAuthority_PropertyId("String")
    , mGetRentalBondAuthority_PropertyId("String")
    , mSetRentalBondAuthority_TenancyId("String")
    , mGetRentalBondAuthority_TenancyId("String")
    , mSetRentalBondAuthority_DocRefIds(["String"])
    , mGetRentalBondAuthority_DocRefIds(["String"])
    , mSetRentalBondAuthority_ImageRefIds(["String"])
    , mGetRentalBondAuthority_ImageRefIds(["String"])
    , mSetATO_ATOId("String")
    , mGetATO_ATOId("String")
    , mSetATO_ContactFirstNameList(["String"])
    , mGetATO_ContactFirstNameList(["String"])
    , mSetATO_ContactLastNameList(["String"])
    , mGetATO_ContactLastNameList(["String"])
    , mSetATO_StreetAddress("String")
    , mGetATO_StreetAddress("String")
    , mSetATO_PostalAddress("String")
    , mGetATO_PostalAddress("String")
    , mSetATO_EmailAddresses(["String"])
    , mGetATO_EmailAddresses(["String"])
    , mSetATO_MobilePhone(["String"])
    , mGetATO_MobilePhone(["String"])
    , mSetATO_WorkPhone(["String"])
    , mGetATO_WorkPhone(["String"])
    , mSetATO_ContactedWithDetails(["String"])
    , mGetATO_ContactedWithDetails(["String"])
    , mSetATO_DocRefIds(["String"])
    , mGetATO_DocRefIds(["String"])
    , mSetATO_BusinessChannelOwnerId("String")
    , mGetATO_BusinessChannelOwnerId("String")
    , mSetASIC_ASICId("String")
    , mGetASIC_ASICId("String")
    , mSetASIC_ContactFirstNameList(["String"])
    , mGetASIC_ContactFirstNameList(["String"])
    , mSetASIC_ContactLastNameList(["String"])
    , mGetASIC_ContactLastNameList(["String"])
    , mSetASIC_StreetAddress("String")
    , mGetASIC_StreetAddress("String")
    , mSetASIC_PostalAddress("String")
    , mGetASIC_PostalAddress("String")
    , mSetASIC_EmailAddresses(["String"])
    , mGetASIC_EmailAddresses(["String"])
    , mSetASIC_MobilePhone(["String"])
    , mGetASIC_MobilePhone(["String"])
    , mSetASIC_WorkPhone(["String"])
    , mGetASIC_WorkPhone(["String"])
    , mSetASIC_ContactedWithDetails(["String"])
    , mGetASIC_ContactedWithDetails(["String"])
    , mSetASIC_DocRefIds(["String"])
    , mGetASIC_DocRefIds(["String"])
    , mSetASIC_ImageRefIds(["String"])
    , mGetASIC_ImageRefIds(["String"])
    , mSetASIC_BusinessChannelOwnerId("String")
    , mGetASIC_BusinessChannelOwnerId("String")
    , mSetACNC_ACNCId("String")
    , mGetACNC_ACNCId("String")
    , mSetACNC_ContactFirstNameList(["String"])
    , mGetACNC_ContactFirstNameList(["String"])
    , mSetACNC_ContactLastNameList(["String"])
    , mGetACNC_ContactLastNameList(["String"])
    , mSetACNC_StreetAddress("String")
    , mGetACNC_StreetAddress("String")
    , mSetACNC_PostalAddress("String")
    , mGetACNC_PostalAddress("String")
    , mSetACNC_EmailAddresses(["String"])
    , mGetACNC_EmailAddresses(["String"])
    , mSetACNC_MobilePhone(["String"])
    , mGetACNC_MobilePhone(["String"])
    , mSetACNC_WorkPhone(["String"])
    , mGetACNC_WorkPhone(["String"])
    , mSetACNC_ContactedWithDetails(["String"])
    , mGetACNC_ContactedWithDetails(["String"])
    , mSetACNC_DocRefIds(["String"])
    , mGetACNC_DocRefIds(["String"])
    , mSetACNC_ImageRefIds(["String"])
    , mGetACNC_ImageRefIds(["String"])
    , mSetACNC_BusinessChannelOwnerId("String")
    , mGetACNC_BusinessChannelOwnerId("String")
    , mSetNationalRegulator_NatRegId("String")
    , mGetNationalRegulator_NatRegId("String")
    , mSetNationalRegulator_NatRegName("String")
    , mGetNationalRegulator_NatRegName("String")
    , mSetNationalRegulator_ContactFirstNameList(["String"])
    , mGetNationalRegulator_ContactFirstNameList(["String"])
    , mSetNationalRegulator_ContactLastNameList(["String"])
    , mGetNationalRegulator_ContactLastNameList(["String"])
    , mSetNationalRegulator_StreetAddress("String")
    , mGetNationalRegulator_StreetAddress("String")
    , mSetNationalRegulator_PostalAddress("String")
    , mGetNationalRegulator_PostalAddress("String")
    , mSetNationalRegulator_EmailAddresses(["String"])
    , mGetNationalRegulator_EmailAddresses(["String"])
    , mSetNationalRegulator_MobilePhone(["String"])
    , mGetNationalRegulator_MobilePhone(["String"])
    , mSetNationalRegulator_WorkPhone(["String"])
    , mGetNationalRegulator_WorkPhone(["String"])
    , mSetNationalRegulator_ContactedWithDetails(["String"])
    , mGetNationalRegulator_ContactedWithDetails(["String"])
    , mSetNationalRegulator_DocRefIds(["String"])
    , mGetNationalRegulator_DocRefIds(["String"])
    , mSetNationalRegulator_ImageRefIds(["String"])
    , mGetNationalRegulator_ImageRefIds(["String"])
    , mSetNationalRegulator_BusinessChannelOwnerId("String")
    , mGetNationalRegulator_BusinessChannelOwnerId("String")
    , mSetStateBasedRegulator_StateBasedRegId("String")
    , mGetStateBasedRegulator_StateBasedRegId("String")
    , mSetStateBasedRegulator_StateBasedRegName("String")
    , mGetStateBasedRegulator_StateBasedRegName("String")
    , mSetStateBasedRegulator_AusState("String")
    , mGetStateBasedRegulator_AusState("String")
    , mSetStateBasedRegulator_ContactFirstNameList(["String"])
    , mGetStateBasedRegulator_ContactFirstNameList(["String"])
    , mSetStateBasedRegulator_ContactLastNameList(["String"])
    , mGetStateBasedRegulator_ContactLastNameList(["String"])
    , mSetStateBasedRegulator_StreetAddress("String")
    , mGetStateBasedRegulator_StreetAddress("String")
    , mSetStateBasedRegulator_PostalAddress("String")
    , mGetStateBasedRegulator_PostalAddress("String")
    , mSetStateBasedRegulator_EmailAddresses(["String"])
    , mGetStateBasedRegulator_EmailAddresses(["String"])
    , mSetStateBasedRegulator_MobilePhone(["String"])
    , mGetStateBasedRegulator_MobilePhone(["String"])
    , mSetStateBasedRegulator_WorkPhone(["String"])
    , mGetStateBasedRegulator_WorkPhone(["String"])
    , mSetStateBasedRegulator_ContactedWithDetails(["String"])
    , mGetStateBasedRegulator_ContactedWithDetails(["String"])
    , mSetStateBasedRegulator_DocRefIds(["String"])
    , mGetStateBasedRegulator_DocRefIds(["String"])
    , mSetStateBasedRegulator_ImageRefIds(["String"])
    , mGetStateBasedRegulator_ImageRefIds(["String"])
    , mSetStateBasedRegulator_BusinessChannelOwnerId("String")
    , mGetStateBasedRegulator_BusinessChannelOwnerId("String")
    , mSetStateLandTitleRegistry_LandTitleRegistryId("String")
    , mGetStateLandTitleRegistry_LandTitleRegistryId("String")
    , mSetStateLandTitleRegistry_AuthorityName("String")
    , mGetStateLandTitleRegistry_AuthorityName("String")
    , mSetStateLandTitleRegistry_AusState("String")
    , mGetStateLandTitleRegistry_AusState("String")
    , mSetStateLandTitleRegistry_ContactFirstNameList(["String"])
    , mGetStateLandTitleRegistry_ContactFirstNameList(["String"])
    , mSetStateLandTitleRegistry_ContactLastNameList(["String"])
    , mGetStateLandTitleRegistry_ContactLastNameList(["String"])
    , mSetStateLandTitleRegistry_StreetAddress("String")
    , mGetStateLandTitleRegistry_StreetAddress("String")
    , mSetStateLandTitleRegistry_PostalAddress("String")
    , mGetStateLandTitleRegistry_PostalAddress("String")
    , mSetStateLandTitleRegistry_Email("String")
    , mGetStateLandTitleRegistry_Email("String")
    , mSetStateLandTitleRegistry_MobilePhone(0)
    , mGetStateLandTitleRegistry_MobilePhone(0)
    , mSetStateLandTitleRegistry_WorkPhone(0)
    , mGetStateLandTitleRegistry_WorkPhone(0)
    , mSetStateLandTitleRegistry_ContactedWithDetails(["String"])
    , mGetStateLandTitleRegistry_ContactedWithDetails(["String"])
    , mSetStateLandTitleRegistry_BusinessChannelOwnerId("String")
    , mGetStateLandTitleRegistry_BusinessChannelOwnerId("String")
    , mSetStateLandTitleRegistry_PropertyId("String")
    , mGetStateLandTitleRegistry_PropertyId("String")
    , mSetStateLandTitleRegistry_DocRefIds(["String"])
    , mGetStateLandTitleRegistry_DocRefIds(["String"])
    , mSetStateLandTitleRegistry_ImageRefIds(["String"])
    , mGetStateLandTitleRegistry_ImageRefIds(["String"])
    , mSetNCAT_TribunalId("String")
    , mGetNCAT_TribunalId("String")
    , mSetNCAT_AuthorityName("String")
    , mGetNCAT_AuthorityName("String")
    , mSetNCAT_AusState("String")
    , mGetNCAT_AusState("String")
    , mSetNCAT_ContactFirstNameList(["String"])
    , mGetNCAT_ContactFirstNameList(["String"])
    , mSetNCAT_ContactLastNameList(["String"])
    , mGetNCAT_ContactLastNameList(["String"])
    , mSetNCAT_StreetAddress("String")
    , mGetNCAT_StreetAddress("String")
    , mSetNCAT_PostalAddress("String")
    , mGetNCAT_PostalAddress("String")
    , mSetNCAT_Email("String")
    , mGetNCAT_Email("String")
    , mSetNCAT_MobilePhone(0)
    , mGetNCAT_MobilePhone(0)
    , mSetNCAT_WorkPhone(0)
    , mGetNCAT_WorkPhone(0)
    , mSetNCAT_CaseDetailsActsResponsesAllegationsRebuttals(["String"])
    , mGetNCAT_CaseDetailsActsResponsesAllegationsRebuttals(["String"])
    , mSetNCAT_DateTimeDetailsInChronologicalOrder(["String"])
    , mGetNCAT_DateTimeDetailsInChronologicalOrder(["String"])
    , mSetNCAT_AdjournedOn(["String"])
    , mGetNCAT_AdjournedOn(["String"])
    , mSetNCAT_AdjournedUntil(["String"])
    , mGetNCAT_AdjournedUntil(["String"])
    , mSetNCAT_ContactedWithDetails(["String"])
    , mGetNCAT_ContactedWithDetails(["String"])
    , mSetNCAT_BusinessChannelOwnerId("String")
    , mGetNCAT_BusinessChannelOwnerId("String")
    , mSetNCAT_PropertyId("String")
    , mGetNCAT_PropertyId("String")
    , mSetNCAT_TenancyId("String")
    , mGetNCAT_TenancyId("String")
    , mSetNCAT_BranchId("String")
    , mGetNCAT_BranchId("String")
    , mSetNCAT_DocRefIds(["String"])
    , mGetNCAT_DocRefIds(["String"])
    , mSetNCAT_ImageRefIds(["String"])
    , mGetNCAT_ImageRefIds(["String"])
{
}

CRegulator::~CRegulator()
{
    // 
}

ECode CRegulator::constructor()
{
    return NOERROR;
}

ECode CRegulator::CompareTo(
    /* [in] */ IInterface* another,
    /* [out] */ Int32* result)
{
    VALIDATE_NOT_NULL(result);

    ICRegulator* oa = ICH::Probe(another);
    if (oa == NULL) {
        *result = 1;
        return E_CLASS_CAST_EXCEPTION;
    }

    CRegulator* a = (CRegulator*)oa;
    *result = mName.Compare(a->mName);
    return NOERROR;
}

ECode CRegulator::SetName(
    /* [in] */ const String& name)
{
    mName = name;
    return NOERROR;
}

ECode CRegulator::GetName(
    /* [out] */ String* name)
{
    VALIDATE_NOT_NULL(name)
    *name = mName;
    return NOERROR;
}

ECode CRegulator::SetAge(
    /* [in] */ Int32 age)
{
    mAge = age;
    return NOERROR;
}

ECode CRegulator::GetAge(
    /* [out] */ Int32* age)
{
    VALIDATE_NOT_NULL(age)
    *age = mAge;
    return NOERROR;
}

ECode CRegulator::CanFly(
    /* [out] */ Boolean* canFly)
{
    VALIDATE_NOT_NULL(canFly);
    *canFly = FALSE;
    return NOERROR;
}

} // ChubbaMorris
} // Elastos

