#include "elastos/chubbamorris/CStakeholder.h"
#include <stdio.h>

using Elastos::Core::EIID_IComparable;

namespace Elastos {
namespace ChubbaMorris {

// The class which implements a CAR interface requires macros CAR_INTERFACE_IMPL/CAR_INTERFACE_IMPL
CAR_INTERFACE_IMPL(CStakeholder, Object, ICH, IComparable)

// Initialize member variables using member initialization lists.
CStakeholder::CStakeholder()
    : mSetGovernmentalStakeholder_GovStakeholderId("String")
    , mGetGovernmentalStakeholder_GovStakeholderId("String")
    , mSetGovernmentalStakeholder_DepartmentName("String")
    , mGetGovernmentalStakeholder_DepartmentName("String")
    , mSetGovernmentalStakeholder_GovLevel("String")
    , mGetGovernmentalStakeholder_GovLevel("String")
    , mSetGovernmentalStakeholder_StakeholderName("String")
    , mGetGovernmentalStakeholder_StakeholderName("String")
    , mSetGovernmentalStakeholder_StakeholderDetails("String")
    , mGetGovernmentalStakeholder_StakeholderDetails("String")
    , mSetGovernmentalStakeholder_ContactFirstNameList(["String"])
    , mGetGovernmentalStakeholder_ContactFirstNameList(["String"])
    , mSetGovernmentalStakeholder_ContactLastNameList(["String"])
    , mGetGovernmentalStakeholder_ContactLastNameList(["String"])
    , mSetGovernmentalStakeholder_ResidentialAddress("String")
    , mGetGovernmentalStakeholder_ResidentialAddress("String")
    , mSetGovernmentalStakeholder_PostalAddress("String")
    , mGetGovernmentalStakeholder_PostalAddress("String")
    , mSetGovernmentalStakeholder_EmailAddresses(["String"])
    , mGetGovernmentalStakeholder_EmailAddresses(["String"])
    , mSetGovernmentalStakeholder_MobilePhone(["String"])
    , mGetGovernmentalStakeholder_MobilePhone(["String"])
    , mSetGovernmentalStakeholder_WorkPhone(["String"])
    , mGetGovernmentalStakeholder_WorkPhone(["String"])
    , mSetGovernmentalStakeholder_ContactedWithDetails(["String"])
    , mGetGovernmentalStakeholder_ContactedWithDetails(["String"])
    , mSetGovernmentalStakeholder_DocRefIds(["String"])
    , mGetGovernmentalStakeholder_DocRefIds(["String"])
    , mSetGovernmentalStakeholder_ImageRefIds(["String"])
    , mGetGovernmentalStakeholder_ImageRefIds(["String"])
    , mSetGovernmentalStakeholder_BusinessDirectorIds(["String"])
    , mGetGovernmentalStakeholder_BusinessDirectorIds(["String"])
    , mSetGovernmentalStakeholder_BusinessChannelOwnerId("String")
    , mGetGovernmentalStakeholder_BusinessChannelOwnerId("String")
    , mSetNonGovernmentalStakeholder_NonGovStakeholderId("String")
    , mGetNonGovernmentalStakeholder_NonGovStakeholderId("String")
    , mSetNonGovernmentalStakeholder_ABN("String")
    , mGetNonGovernmentalStakeholder_ABN("String")
    , mSetNonGovernmentalStakeholder_StakeholderName("String")
    , mGetNonGovernmentalStakeholder_StakeholderName("String")
    , mSetNonGovernmentalStakeholder_StakeholderDetails("String")
    , mGetNonGovernmentalStakeholder_StakeholderDetails("String")
    , mSetNonGovernmentalStakeholder_ContactFirstNameList(["String"])
    , mGetNonGovernmentalStakeholder_ContactFirstNameList(["String"])
    , mSetNonGovernmentalStakeholder_ContactLastNameList(["String"])
    , mGetNonGovernmentalStakeholder_ContactLastNameList(["String"])
    , mSetNonGovernmentalStakeholder_ResidentialAddress("String")
    , mGetNonGovernmentalStakeholder_ResidentialAddress("String")
    , mSetNonGovernmentalStakeholder_PostalAddress("String")
    , mGetNonGovernmentalStakeholder_PostalAddress("String")
    , mSetNonGovernmentalStakeholder_EmailAddresses(["String"])
    , mGetNonGovernmentalStakeholder_EmailAddresses(["String"])
    , mSetNonGovernmentalStakeholder_MobilePhone(["String"])
    , mGetNonGovernmentalStakeholder_MobilePhone(["String"])
    , mSetNonGovernmentalStakeholder_WorkPhone(["String"])
    , mGetNonGovernmentalStakeholder_WorkPhone(["String"])
    , mSetNonGovernmentalStakeholder_ContactedWithDetails(["String"])
    , mGetNonGovernmentalStakeholder_ContactedWithDetails(["String"])
    , mSetNonGovernmentalStakeholder_DocRefIds(["String"])
    , mGetNonGovernmentalStakeholder_DocRefIds(["String"])
    , mSetNonGovernmentalStakeholder_ImageRefIds(["String"])
    , mGetNonGovernmentalStakeholder_ImageRefIds(["String"])
    , mSetNonGovernmentalStakeholder_BusinessDirectorIds(["String"])
    , mGetNonGovernmentalStakeholder_BusinessDirectorIds(["String"])
    , mSetNonGovernmentalStakeholder_BusinessChannelOwnerId("String")
    , mGetNonGovernmentalStakeholder_BusinessChannelOwnerId("String")
    , mSetPartner_PartnerId("String")
    , mGetPartner_PartnerId("String")
    , mSetPartner_ABN("String")
    , mGetPartner_ABN("String")
    , mSetPartner_PartnerName("String")
    , mGetPartner_PartnerName("String")
    , mSetPartner_ContactFirstNameList(["String"])
    , mGetPartner_ContactFirstNameList(["String"])
    , mSetPartner_ContactLastNameList(["String"])
    , mGetPartner_ContactLastNameList(["String"])
    , mSetPartner_ResidentialAddress("String")
    , mGetPartner_ResidentialAddress("String")
    , mSetPartner_PostalAddress("String")
    , mGetPartner_PostalAddress("String")
    , mSetPartner_EmailAddresses(["String"])
    , mGetPartner_EmailAddresses(["String"])
    , mSetPartner_MobilePhone(["String"])
    , mGetPartner_MobilePhone(["String"])
    , mSetPartner_WorkPhone(["String"])
    , mGetPartner_WorkPhone(["String"])
    , mSetPartner_ContactedWithDetails(["String"])
    , mGetPartner_ContactedWithDetails(["String"])
    , mSetPartner_BusinessChannelOwnerId("String")
    , mGetPartner_BusinessChannelOwnerId("String")
    , mSetPartner_BranchId("String")
    , mGetPartner_BranchId("String")
    , mSetPartner_DocRefIds(["String"])
    , mGetPartner_DocRefIds(["String"])
    , mSetPartner_ImageRefIds(["String"])
    , mGetPartner_ImageRefIds(["String"])
    , mSetCommunity_CommunityId("String")
    , mGetCommunity_CommunityId("String")
    , mSetCommunity_GroupName("String")
    , mGetCommunity_GroupName("String")
    , mSetCommunity_FirstName("String")
    , mGetCommunity_FirstName("String")
    , mSetCommunity_LastName("String")
    , mGetCommunity_LastName("String")
    , mSetCommunity_ResidentialAddress("String")
    , mGetCommunity_ResidentialAddress("String")
    , mSetCommunity_PostalAddress("String")
    , mGetCommunity_PostalAddress("String")
    , mSetCommunity_EmailAddresses(["String"])
    , mGetCommunity_EmailAddresses(["String"])
    , mSetCommunity_MobilePhone(["String"])
    , mGetCommunity_MobilePhone(["String"])
    , mSetCommunity_HomePhone(["String"])
    , mGetCommunity_HomePhone(["String"])
    , mSetCommunity_WorkPhone(["String"])
    , mGetCommunity_WorkPhone(["String"])
    , mSetCommunity_ContactedWithDetails(["String"])
    , mGetCommunity_ContactedWithDetails(["String"])
    , mSetCommunity_BusinessChannelOwnerId("String")
    , mGetCommunity_BusinessChannelOwnerId("String")
    , mSetCommunity_BranchId("String")
    , mGetCommunity_BranchId("String")
    , mSetCommunity_DocRefIds(["String"])
    , mGetCommunity_DocRefIds(["String"])
    , mSetCommunity_ImageRefIds(["String"])
    , mGetCommunity_ImageRefIds(["String"])
    , mSetMedia_MediaId("String")
    , mGetMedia_MediaId("String")
    , mSetMedia_ABN("String")
    , mGetMedia_ABN("String")
    , mSetMedia_CompanyName("String")
    , mGetMedia_CompanyName("String")
    , mSetMedia_ContactFirstNameList(["String"])
    , mGetMedia_ContactFirstNameList(["String"])
    , mSetMedia_ContactLastNameList(["String"])
    , mGetMedia_ContactLastNameList(["String"])
    , mSetMedia_ResidentialAddress("String")
    , mGetMedia_ResidentialAddress("String")
    , mSetMedia_PostalAddress("String")
    , mGetMedia_PostalAddress("String")
    , mSetMedia_EmailAddresses(["String"])
    , mGetMedia_EmailAddresses(["String"])
    , mSetMedia_MobilePhone(["String"])
    , mGetMedia_MobilePhone(["String"])
    , mSetMedia_WorkPhone(["String"])
    , mGetMedia_WorkPhone(["String"])
    , mSetMedia_ContactedWithDetails(["String"])
    , mGetMedia_ContactedWithDetails(["String"])
    , mSetMedia_BusinessChannelOwnerId("String")
    , mGetMedia_BusinessChannelOwnerId("String")
    , mSetMedia_BranchId("String")
    , mGetMedia_BranchId("String")
    , mSetMedia_DocRefIds(["String"])
    , mGetMedia_DocRefIds(["String"])
    , mSetMedia_ImageRefIds(["String"])
    , mGetMedia_ImageRefIds(["String"])
    , mSetTICA_TicaId("String")
    , mGetTICA_TicaId("String")
    , mSetTICA_TicaUserName("String")
    , mGetTICA_TicaUserName("String")
    , mSetTICA_TICAPassword("String")
    , mGetTICA_TICAPassword("String")
    , mSetTICA_TenantFirstName("String")
    , mGetTICA_TenantFirstName("String")
    , mSetTICA_TenantMiddleInitialOrName("String")
    , mGetTICA_TenantMiddleInitialOrName("String")
    , mSetTICA_TenantLastName("String")
    , mGetTICA_TenantLastName("String")
    , mSetTICA_TenantDateOfBirth("String")
    , mGetTICA_TenantDateOfBirth("String")
    , mSetTICA_ApplicantFirstName("String")
    , mGetTICA_ApplicantFirstName("String")
    , mSetTICA_ApplicantMiddleInitialOrName("String")
    , mGetTICA_ApplicantMiddleInitialOrName("String")
    , mSetTICA_ApplicantLastName("String")
    , mGetTICA_ApplicantLastName("String")
    , mSetTICA_ApplicantDateOfBirth("String")
    , mGetTICA_ApplicantDateOfBirth("String")
    , mSetTICA_BusinessChannelOwnerId("String")
    , mGetTICA_BusinessChannelOwnerId("String")
    , mSetTICA_BranchId("String")
    , mGetTICA_BranchId("String")
    , mSetTICA_DocRefIds(["String"])
    , mGetTICA_DocRefIds(["String"])
    , mSetTICA_ImageRefIds(["String"])
    , mGetTICA_ImageRefIds(["String"])
    , mSetTICA_ApplicantId("String")
    , mGetTICA_ApplicantId("String")
    , mSetTICA_TenancyId("String")
    , mGetTICA_TenancyId("String")
    , mSetAgent_AgentId("String")
    , mGetAgent_AgentId("String")
    , mSetAgent_ABN("String")
    , mGetAgent_ABN("String")
    , mSetAgent_AgencyName("String")
    , mGetAgent_AgencyName("String")
    , mSetAgent_AgentType("String")
    , mGetAgent_AgentType("String")
    , mSetAgent_DescriptionOfAgency("String")
    , mGetAgent_DescriptionOfAgency("String")
    , mSetAgent_ContactFirstNameList(["String"])
    , mGetAgent_ContactFirstNameList(["String"])
    , mSetAgent_ContactLastNameList(["String"])
    , mGetAgent_ContactLastNameList(["String"])
    , mSetAgent_ResidentialAddress("String")
    , mGetAgent_ResidentialAddress("String")
    , mSetAgent_PostalAddress("String")
    , mGetAgent_PostalAddress("String")
    , mSetAgent_EmailAddresses(["String"])
    , mGetAgent_EmailAddresses(["String"])
    , mSetAgent_MobilePhone(["String"])
    , mGetAgent_MobilePhone(["String"])
    , mSetAgent_WorkPhone(["String"])
    , mGetAgent_WorkPhone(["String"])
    , mSetAgent_ContactedWithDetails(["String"])
    , mGetAgent_ContactedWithDetails(["String"])
    , mSetAgent_DocRefIds(["String"])
    , mGetAgent_DocRefIds(["String"])
    , mSetAgent_ImageRefIds(["String"])
    , mGetAgent_ImageRefIds(["String"])
    , mSetAgent_AgentTypeId("String")
    , mGetAgent_AgentTypeId("String")
    , mSetAgent_BusinessDirectorIds(["String"])
    , mGetAgent_BusinessDirectorIds(["String"])
    , mSetAgent_BusinessChannelOwnerId("String")
    , mGetAgent_BusinessChannelOwnerId("String")
    , mSetAgentType_AgentTypeId("String")
    , mGetAgentType_AgentTypeId("String")
    , mSetAgentType_AgentType("String")
    , mGetAgentType_AgentType("String")
    , mSetAgentType_AgentTypeDescription("String")
    , mGetAgentType_AgentTypeDescription("String")
    , mSetAgentType_BusinessChannelOwnerId("String")
    , mGetAgentType_BusinessChannelOwnerId("String")
    , mSetAgentType_BranchId("String")
    , mGetAgentType_BranchId("String")
    , mSetAgentType_DeptId("String")
    , mGetAgentType_DeptId("String")
    , mSetAgentType_ServiceIds(["String"])
    , mGetAgentType_ServiceIds(["String"])
    , mSetAgentType_SupplierTypeIds(["String"])
    , mGetAgentType_SupplierTypeIds(["String"])
    , mSetAgentType_StateBasedRegId("String")
    , mGetAgentType_StateBasedRegId("String")
    , mSetAgentType_NatRegId("String")
    , mGetAgentType_NatRegId("String")
    , mSetAgentType_DocRefIds(["String"])
    , mGetAgentType_DocRefIds(["String"])
    , mSetAgentType_ImageRefIds(["String"])
    , mGetAgentType_ImageRefIds(["String"])
    , mSetAgentType_VideoRefIds(["String"])
    , mGetAgentType_VideoRefIds(["String"])
    , mSetStateLAHAuthority_StateLAHAuthorityId("String")
    , mGetStateLAHAuthority_StateLAHAuthorityId("String")
    , mSetStateLAHAuthority_AuthorityName("String")
    , mGetStateLAHAuthority_AuthorityName("String")
    , mSetStateLAHAuthority_AusState("String")
    , mGetStateLAHAuthority_AusState("String")
    , mSetStateLAHAuthority_ContactFirstNameList(["String"])
    , mGetStateLAHAuthority_ContactFirstNameList(["String"])
    , mSetStateLAHAuthority_ContactLastNameList(["String"])
    , mGetStateLAHAuthority_ContactLastNameList(["String"])
    , mSetStateLAHAuthority_StreetAddress("String")
    , mGetStateLAHAuthority_StreetAddress("String")
    , mSetStateLAHAuthority_PostalAddress("String")
    , mGetStateLAHAuthority_PostalAddress("String")
    , mSetStateLAHAuthority_EmailAddresses(["String"])
    , mGetStateLAHAuthority_EmailAddresses(["String"])
    , mSetStateLAHAuthority_MobilePhone(["String"])
    , mGetStateLAHAuthority_MobilePhone(["String"])
    , mSetStateLAHAuthority_WorkPhone(["String"])
    , mGetStateLAHAuthority_WorkPhone(["String"])
    , mSetStateLAHAuthority_ContactedWithDetails(["String"])
    , mGetStateLAHAuthority_ContactedWithDetails(["String"])
    , mSetStateLAHAuthority_BusinessChannelOwnerId("String")
    , mGetStateLAHAuthority_BusinessChannelOwnerId("String")
    , mSetStateLAHAuthority_BranchId("String")
    , mGetStateLAHAuthority_BranchId("String")
    , mSetStateLAHAuthority_DocRefIds(["String"])
    , mGetStateLAHAuthority_DocRefIds(["String"])
    , mSetStateLAHAuthority_ImageRefIds(["String"])
    , mGetStateLAHAuthority_ImageRefIds(["String"])
    , mSetStateLAHAuthority_PropertyOwnerId("String")
    , mGetStateLAHAuthority_PropertyOwnerId("String")
    , mSetStatePublicHousingAuthority_StatePublicHousingAuthorityId("String")
    , mGetStatePublicHousingAuthority_StatePublicHousingAuthorityId("String")
    , mSetStatePublicHousingAuthority_AuthorityName("String")
    , mGetStatePublicHousingAuthority_AuthorityName("String")
    , mSetStatePublicHousingAuthority_ContactFirstNameList(["String"])
    , mGetStatePublicHousingAuthority_ContactFirstNameList(["String"])
    , mSetStatePublicHousingAuthority_ContactLastNameList(["String"])
    , mGetStatePublicHousingAuthority_ContactLastNameList(["String"])
    , mSetStatePublicHousingAuthority_StreetAddress("String")
    , mGetStatePublicHousingAuthority_StreetAddress("String")
    , mSetStatePublicHousingAuthority_PostalAddress("String")
    , mGetStatePublicHousingAuthority_PostalAddress("String")
    , mSetStatePublicHousingAuthority_EmailAddresses(["String"])
    , mGetStatePublicHousingAuthority_EmailAddresses(["String"])
    , mSetStatePublicHousingAuthority_MobilePhone(["String"])
    , mGetStatePublicHousingAuthority_MobilePhone(["String"])
    , mSetStatePublicHousingAuthority_WorkPhone(["String"])
    , mGetStatePublicHousingAuthority_WorkPhone(["String"])
    , mSetStatePublicHousingAuthority_ContactedWithDetails(["String"])
    , mGetStatePublicHousingAuthority_ContactedWithDetails(["String"])
    , mSetStatePublicHousingAuthority_AusState("String")
    , mGetStatePublicHousingAuthority_AusState("String")
    , mSetStatePublicHousingAuthority_BranchId("String")
    , mGetStatePublicHousingAuthority_BranchId("String")
    , mSetStatePublicHousingAuthority_DocRefIds(["String"])
    , mGetStatePublicHousingAuthority_DocRefIds(["String"])
    , mSetStatePublicHousingAuthority_ImageRefIds(["String"])
    , mGetStatePublicHousingAuthority_ImageRefIds(["String"])
    , mSetStatePublicHousingAuthority_PropertyOwnerId("String")
    , mGetStatePublicHousingAuthority_PropertyOwnerId("String")
    , mSetStatePublicHousingAuthority_BusinessChannelOwnerId("String")
    , mGetStatePublicHousingAuthority_BusinessChannelOwnerId("String")
{
}

CStakeholder::~CStakeholder()
{
    // 
}

ECode CStakeholder::constructor()
{
    return NOERROR;
}

ECode CStakeholder::CompareTo(
    /* [in] */ IInterface* another,
    /* [out] */ Int32* result)
{
    VALIDATE_NOT_NULL(result);

    ICStakeholder* oa = ICH::Probe(another);
    if (oa == NULL) {
        *result = 1;
        return E_CLASS_CAST_EXCEPTION;
    }

    CStakeholder* a = (CStakeholder*)oa;
    *result = mName.Compare(a->mName);
    return NOERROR;
}

ECode CStakeholder::SetName(
    /* [in] */ const String& name)
{
    mName = name;
    return NOERROR;
}

ECode CStakeholder::GetName(
    /* [out] */ String* name)
{
    VALIDATE_NOT_NULL(name)
    *name = mName;
    return NOERROR;
}

ECode CStakeholder::SetAge(
    /* [in] */ Int32 age)
{
    mAge = age;
    return NOERROR;
}

ECode CStakeholder::GetAge(
    /* [out] */ Int32* age)
{
    VALIDATE_NOT_NULL(age)
    *age = mAge;
    return NOERROR;
}

ECode CStakeholder::CanFly(
    /* [out] */ Boolean* canFly)
{
    VALIDATE_NOT_NULL(canFly);
    *canFly = FALSE;
    return NOERROR;
}

} // ChubbaMorris
} // Elastos

